### ISSUE TITLE
Small typo in FGCP_DualAZ_ExistingVPC.template.json

### ISSUE THREAD

**Issue by FortiJeremy** [fortinet/aws-cloudformation-templates#11]
For the FortiGate2 parameters, the description references the wrong subnets.
Line 177, 184, 191, 198 all should read "...Subnet2" instead of "...Subnet1"

Non impacting as long as the correct subnets are referenced, but confusing for users.

**Comment by mobilesuitzero** [comment]
Should be fixed in the PR.

https://github.com/fortinet/aws-cloudformation-templates/pull/37
