### ISSUE TITLE
Minor modification required

### ISSUE THREAD

**Issue by laptom** [fortinet/aws-cloudformation-templates#17]
Due to requirements I need this IaaC to be slightly modified. 
I need two EIPs to be assigned - appreciate if someone more knowledgable can help! thx.

**Existing:**

fgt1eni0: ClusterEIP - associated with PublicIP of Active FG

Interface IP Configuration for FortiGate 1:
FortiGate1PublicIP  - 10.0.1.10/24

Interface IP Configuration for FortiGate 2:
FortiGate2PublicIP - 10.0.10.10/24

**Expected:**

Interface IP Configuration for FortiGate 1:
FortiGate1PublicIP  - 10.0.1.10/24
FortiGate1PublicIP  - 10.0.1.11/24 - secondary address

Interface IP Configuration for FortiGate 2:
FortiGate2PublicIP - 10.0.10.10/24
FortiGate2PublicIP - 10.0.10.11/24 - secondary address

fgt1eni0: ClusterEIP - associated with  PublicIP of Active FG
fgt1eni0: ClusterEIP2 - associated with second  PublicIP of Active FG

**Comment by mobilesuitzero** [comment]
User can deploy the setup first and then manually added the second cluster eip manually afterwards.
