### ISSUE TITLE
Does FortiOS FGCP AP HA (Dual AZ) in AWS use network loadbalancer?

### ISSUE THREAD

**Issue by lplpmc** [fortinet/aws-cloudformation-templates#25]
Does this deployment template use network loadbalancer w/ vpc endpoints?  Does the SDN connector update all routing tables? I.e. routing tables in sub accounts? 

Does this deployment support east/west inspection with TGW?

**Comment by mobilesuitzero** [comment]
Hi,

The dual AZ HA A-P Cloud formation doesn't use load balancer, and nor vpc endpoints. 

SDN Connector will only update the routes that are pointed to the eni of the interface of the primary unit.  

https://docs.fortinet.com/document/fortigate-public-cloud/7.2.0/aws-administration-guide/229470/deploying-fortigate-vm-active-passive-ha-aws-between-multiple-zones

This deployment doesn't have transit gateway integration, you can take a look at the other repo.

https://github.com/fortinet/fortigate-terraform-deploy/tree/main/aws/7.2

And, see if that helps.

Cheers

**Comment by lplpmc** [comment]
> 

Thank you! I prefer terraform anyway, I think this directory is what I am looking for after taking a look at your link https://github.com/fortinet/fortigate-terraform-deploy/tree/main/aws/7.2/ha-endpoint

**Comment by mobilesuitzero** [comment]
Hi lplpmc

Glad that work for you.  

Will close this issue then.

Cheers
