### ISSUE TITLE
Routing issue in DualAZ

### ISSUE THREAD

**Issue by thatsdanish** [fortinet/aws-cloudformation-templates#31]
I have used dualAZ template however traffic from my instances is not reaching to fortinet firewall cluster..i am not seeing any logs in forward traffic console..i have verified the vpc routing and it seems fine, default route is pointing towards active member.do i need to add some routes in "Static Routes" section as well inside the firewalls ?

**Comment by mobilesuitzero** [comment]
Hi @thatsdanish 

I would probably check couple places.

1.  Check if FortiGate has received the traffic.  
https://community.fortinet.com/t5/FortiGate/Technical-Tip-Packet-capture-sniffer/ta-p/198313
2.  And, if there is firewall policy/route to allow the traffic to go out?
3. Check if the sg/acl is allowing the traffic.

Cheers
