### ISSUE TITLE
Which template to use for fortinet HA deployment at AWS with Flex Licence Toke.

### ISSUE THREAD

**Issue by DevOpsOTL** [fortinet/aws-cloudformation-templates#34]
We are having Fortinet Flex Token based licences.
We want to deploy fortinent firewall at AWS Cloud in HA mode.
I found template which uses PAYG & BYOL with .lic file but I don't found any template which make use of Flex token based licence.

**Comment by mobilesuitzero** [comment]
Hi,

Currently, there isn't any at the moment.

Cheers
