### ISSUE TITLE
AMI issues

### ISSUE THREAD

**Issue by chaddyer123** [fortinet/aws-cloudformation-templates#7]
I am attempting to deploy 6.0 HA via the stack and am getting the following errors:

2021-01-27 14:22:56 UTC-0700 | Fgt1 | CREATE_FAILED | API: ec2:RunInstances Not authorized for images: [ami-0545ab5cfcb04ae1f]
-- | -- | -- | --
2021-01-27 14:22:56 UTC-0700 | Fgt2 | CREATE_FAILED | API: ec2:RunInstances Not authorized for images: [ami-0545ab5cfcb04ae1f]

Is there anything that can be done to correct this?

**Comment by hgaberra** [comment]
Currently there are no public AMIs for FortiOS 6.0.x or older code as this is at EoES (reference the software lifecycle in your support account for more details).  

<img width="1440" alt="Screen Shot 2021-02-04 at 9 22 37 AM" src="https://user-images.githubusercontent.com/24656540/106906125-dcdf9800-66ca-11eb-9cc6-f56c2932ce98.png">

The earliest available public AMI is FortiOS 6.2.5 GA.

The recommendation is to use the 6.2 templates to deploy FGCP in either single or dual AZ fashion.  The templates are located below.
https://github.com/fortinet/aws-cloudformation-templates/tree/main/HA/6.2
